### ISSUE TITLE
src\app.scss: Jest worker encountered 4 child process exceptions, exceeding retry limit

### ISSUE THREAD

**Issue by lipei123321** [wuba/taro-playground#106]
transform[stderr]: D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:27460
transform[stderr]:       throw error;
transform[stderr]:       ^
transform[stderr]:
transform[stderr]: Error: Invalid argument(s): Uri d:%5CcodeFlie%5Cgit%5Ctaro%5Ctaro-playground%5Csrc%5Cstyles%5Ccommon.scss must have scheme 'file:'.
transform[stderr]:     at Object.wrapException (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:1240:17)
transform[stderr]:     at WindowsStyle.pathFromUri$1 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:33270:17)
transform[stderr]:     at StaticClosure.fromUri (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:16166:37)
transform[stderr]:     at Object.NullableExtension_andThen0 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:18492:40)
transform[stderr]:     at Object._wrapException (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:13049:14)
transform[stderr]:     at _render_closure1.call$2 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:82164:21)
transform[stderr]:     at _RootZone.runBinary$3$3 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:27587:18)
transform[stderr]:     at _FutureListener.handleError$1 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:26136:19)
transform[stderr]:     at _Future__propagateToListeners_handleError.call$0 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:26434:49)
transform[stderr]:     at Object._Future__propagateToListeners (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:4550:77) {
transform[stderr]:   dartException: <ref *1> ArgumentError {
transform[stderr]:     _hasValue: false,
transform[stderr]:     invalidValue: null,
transform[stderr]:     name: null,
transform[stderr]:     message: "Uri d:%5CcodeFlie%5Cgit%5Ctaro%5Ctaro-playground%5Csrc%5Cstyles%5Ccommon.scss must have scheme 'file:'.",
transform[stderr]:     '$thrownJsError': <ref *2> Error: Invalid argument(s): Uri d:%5CcodeFlie%5Cgit%5Ctaro%5Ctaro-playground%5Csrc%5Cstyles%5Ccommon.scss must have scheme 'file:'.
transform[stderr]:         at Object.wrapException (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:1240:17)
transform[stderr]:         at WindowsStyle.pathFromUri$1 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:33270:17)
transform[stderr]:         at StaticClosure.fromUri (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:16166:37)
transform[stderr]:         at Object.NullableExtension_andThen0 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:18492:40)
transform[stderr]:         at Object._wrapException (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:13049:14)
transform[stderr]:         at _render_closure1.call$2 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:82164:21)
transform[stderr]:         at _RootZone.runBinary$3$3 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:27587:18)
transform[stderr]:         at _FutureListener.handleError$1 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:26136:19)
transform[stderr]:         at _Future__propagateToListeners_handleError.call$0 (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:26434:49)
transform[stderr]:         at Object._Future__propagateToListeners (D:\codeFlie\git\taro\taro-playground\node_modules\@tarojs\rn-style-transformer\node_modules\sass\sass.dart.js:4550:77) {
transform[stderr]:       dartException: [Circular *1],
transform[stderr]:       '$cachedTrace': _StackTrace {
transform[stderr]:         _exception: [Circular *2],
transform[stderr]:         _trace: "Error: Invalid argument(s): Uri d:%5CcodeFlie%5Cgit%5Ctaro%5Ctaro-playground%5Csrc%5Cstyles%5Ccommon.scss must have scheme 'file:'.\n" +
transform[stderr]:           '    at Object.wrapException (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:1240:17)\n' +
transform[stderr]:           '    at WindowsStyle.pathFromUri$1 (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:33270:17)\n' +
transform[stderr]:           '    at StaticClosure.fromUri (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:16166:37)\n' +
transform[stderr]:           '    at Object.NullableExtension_andThen0 (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:18492:40)\n' +
transform[stderr]:           '    at Object._wrapException (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:13049:14)\n' +
transform[stderr]:           '    at _render_closure1.call$2 (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:82164:21)\n' +
transform[stderr]:           '    at _RootZone.runBinary$3$3 (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:27587:18)\n' +
transform[stderr]:           '    at _FutureListener.handleError$1 (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:26136:19)\n' +
transform[stderr]:           '    at _Future__propagateToListeners_handleError.call$0 (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:26434:49)\n' 
+
transform[stderr]:           '    at Object._Future__propagateToListeners (D:\\codeFlie\\git\\taro\\taro-playground\\node_modules\\@tarojs\\rn-style-transformer\\node_modules\\sass\\sass.dart.js:4550:77)'
transform[stderr]:       }
transform[stderr]:     }
transform[stderr]:   }
transform[stderr]: }
transform[stdout]:

error src\app.scss: Jest worker encountered 4 child process exceptions, exceeding retry limit.
Error: Jest worker encountered 4 child process exceptions, exceeding retry limit
    at ChildProcessWorker.initialize (D:\codeFlie\git\taro\taro-playground\node_modules\jest-worker\build\workers\ChildProcessWorker.js:185:21)
    at ChildProcessWorker._onExit (D:\codeFlie\git\taro\taro-playground\node_modules\jest-worker\build\workers\ChildProcessWorker.js:269:12)
    at ChildProcess.emit (node:events:513:28)

**Comment by fgy888** [comment]
我是这样解决的：package.json 新增 https://github.com/NervJS/taro/issues/11588#issuecomment-1091090510
